### ISSUE TITLE
Emails automáticos não estão funcionando

### ISSUE THREAD

**Issue by symnat** [nucleo-digital/plataforma-taturana#101]
No doc Administração Taturana, item 2b. COMUNICAÇÃO COM EMBAIXADORES.

São emails automáticos que a plataforma envia para os embaixadores que tem sessão agendada e relatório a preencher

**Comment by guilhermecomum** [comment]
> Próximas sessões - mandar email com lembrete - 8 dias antes

mensagem: 

Título: "Você tem uma sessão agendada"

Confirmação da sessão: _dados da sessão_ 
Por favor, responda este email confirmando para receber o link.

(Elas recebem email com a confirmação e respondem email com link, login e senha.)

> Mandar lembretes para preencher relatório - 40h depois (soft)

Título: "Preencha o relatório da sessão do dia DD/MM""

Não esqueça de preencher o relatório da sessão _dados da sessão_:

> página de embaixador logado
> Obrigada.
> 
> Caso não tenha enviado relatório, mandar email 1 semana após a sessão.

Título: "Algo errado? Preencha o relatório da sessão do dia DD/MM""

Ei! Você precisa de alguma ajuda?
Vimos que você ainda não preencheu o relatório da sessão _dados da sessão_.
Vamos lá?

> página de embaixador logado

**Comment by symnat** [comment]
Fluxo de emails revisado:

https://docs.google.com/document/d/1LP4mv8mAwwjb0WBumOJ_pS_8Jx9bPxRxneHkOT5ePAA/edit
