### ISSUE TITLE
Página de Filmes / diferenciação entre Difusão e Portfólio

### ISSUE THREAD

**Issue by symnat** [nucleo-digital/plataforma-taturana#102]
Na página “Filmes”, não há diferenciação entre o que é “portfólio” e o que está em “difusão”. É preciso inserir os elementos gráfico de diferenciação.

Vamos criar layout e te passamos.

**Comment by guilhermecomum** [comment]
FILMES | EM DIFUSÃO

ou 

FILMES | PORTFÓLIO
