### ISSUE TITLE
Gerencie Sessões - lista de filmes

### ISSUE THREAD

**Issue by symnat** [nucleo-digital/plataforma-taturana#108]
Em gerencie sessões: precisamos poder ver a lista total de sessões de um filme e não apenas a lista mensal. E precisamos poder exportar o conjunto das sessões de um filme para um csv.

**Comment by diegothimm** [comment]
Lista OK. No csv está faltando o email do embaixador e data que inscrição (criação) na plataforma.

**Comment by diegothimm** [comment]
No csv das sessões ainda não está guardando a data de criação da sessão na plataforma. E de vários filmes o botão para exportar o CSV não está funcionando (Paratodos/ Comer o Quê?/ Bikes/ India's/ Sem Pena/ 20 Centavos/ Viagem de Yoani/ Ilegal)

**Comment by aluappinheiro** [comment]
Diego, o campo de data de criação da sessão não existia até semana passada. Então apenas sessões cadastradas posterior a este incremento terão este dado.

**Comment by aluappinheiro** [comment]
Resolvida a questão dos csvs

**Comment by diegothimm** [comment]
Issue OK!
