### ISSUE TITLE
Home > Carrosel filmes

### ISSUE THREAD

**Issue by symnat** [nucleo-digital/plataforma-taturana#113]
Na página “Home”, no “carrossel” de filmes, ao clicar em “Mais Informações”, a página do filme não abre.

**Comment by carolmisorelli** [comment]
Aqui tb aparecem alguns erros no texto

![bug3](https://cloud.githubusercontent.com/assets/19521806/15457112/dbae4574-2059-11e6-9efe-6c572d9ff488.png)
