### ISSUE TITLE
Textos Agendar Sessão

### ISSUE THREAD

**Issue by symnat** [nucleo-digital/plataforma-taturana#122]
A sinopse do filme aparece com as tags hmtl

**Comment by carolmisorelli** [comment]
![bug1](https://cloud.githubusercontent.com/assets/19521806/15457101/a524a16a-2059-11e6-8188-4fcd39f21484.png)
![bug3](https://cloud.githubusercontent.com/assets/19521806/15457104/acf63a48-2059-11e6-9393-93946fad3c08.png)

**Comment by guilhermecomum** [comment]
![bug2](https://cloud.githubusercontent.com/assets/19521806/15457130/236d0800-205a-11e6-8f38-8dbbedca24be.png)
