### ISSUE TITLE
Gerencie Sessões - alterar ordem de visualização das sessões agendadas

### ISSUE THREAD

**Issue by symnat** [nucleo-digital/plataforma-taturana#146]
No Gerencie Sessões, como Admin, é importante ter um filtro para alterar a ordem das sessões entre “Data que será a sessão” e Data de inserção.

**Comment by aluappinheiro** [comment]
Por padrão a listagem já vem por data do evento, bastando filtrar por data de inserção para operar desta forma.
Não estávamos armazenando a data de criação das sessões, adicionei este campo. Portanto, com as sessões já cadastradas não temos uma precisão grande sobre a posição dos ítens na listagem.

**Comment by diegothimm** [comment]
Issue OK
