### ISSUE TITLE
Admin - poderes de edição sobre sessões

### ISSUE THREAD

**Issue by symnat** [nucleo-digital/plataforma-taturana#148]
É necessário que o Admin possa alterar a data de qualquer sessão agendada.

**Comment by diegothimm** [comment]
Issue OK. Obs: quando atualizo uma sessão de algum embaixador, ele troca o login(email) do embaixador pelo login do admin.

**Comment by diegothimm** [comment]
Agora ele está apagando o login. Quando atualizo ele não salva nenhum email de embaixador

**Comment by diegothimm** [comment]
Paula, essa é uma das sessões que atualizei e ele está apagando o login(email/embaixador): http://beta.taturanamobi.com.br/adm/session/c0dbb15908f8a18b909f3a0a

**Comment by diegothimm** [comment]
Issue OK!
