### ISSUE TITLE
Embaixador - Sessões marcadas como rascunho

### ISSUE THREAD

**Issue by symnat** [nucleo-digital/plataforma-taturana#149]
Quando o Admin marcar uma sessão como rascunho, é necessário que o embaixador possa editar uma sessão com a data já passada.

**Comment by aluappinheiro** [comment]
Preciso de mais detalhamentos para poder implementar.

**Comment by diegothimm** [comment]
No Gerencie Sessões, logado como Admin conseguimos marcar as sessões como Rascunho. Neste caso, quando marcarmos como Rascunho, as sessões devem ser editáveis pelo usuário. Hoje, uma sessão com uma data que já passou, não está aberta para edição do  usuário.

**Comment by diegothimm** [comment]
Uma sessão marcada como Rascunho, ainda não está aberta para edição do usuário.

**Comment by diegothimm** [comment]
Ainda não está aberta para edição do embaixador, quando marcado pelo Admin como rascunho.

**Comment by aluappinheiro** [comment]
Tens como me passar o link de edição desta sessão?
