### ISSUE TITLE
Gerencie Embaixadores - gravar data de inscrição no site

### ISSUE THREAD

**Issue by symnat** [nucleo-digital/plataforma-taturana#152]
No Gerencie Embaixadores é necessário adicionar nas informações dos embaixadores, a data em que ele se inscreveu na plataforma. 

Incluir também este dado no Exportar CSV.

**Comment by diegothimm** [comment]
Está aparecendo sempre a data corrente, não a data de criação. E não está salvando no csvs.

**Comment by aluappinheiro** [comment]
Diego, aqui aparece a data de criação certinho. Tens como me enviar um print da tela?
A questão do csv já foi resolvida.

**Comment by diegothimm** [comment]
Oi Paula! Agora está aparecendo certo. Issue OK!
