### ISSUE TITLE
Embaixador logado - Sessão cadastrada

### ISSUE THREAD

**Issue by symnat** [nucleo-digital/plataforma-taturana#153]
após incluir uma sessão, ao enviar a pessoa cai na mesma página de cadastro de   sessão, mas com o endereço salvo. Sugiro ao enviar, a pessoa caia na página em que ela enxerga sua própria sessão. - adicionamos mensagem de confirmação “Sessão salva com sucesso” - usuário precisa cair na parte de EDITE SUAS SESSÕES.

**Comment by symnat** [comment]
Carol: é prioritário, nós precisamos que ele caia na página em que enxerga a sua sessão. 100% dos usuários que testaram apontaram para isso. Eles não veem a mensagem de confirmação da sessão.

**Comment by diegothimm** [comment]
Podemos inverter a ordem das seções da página: "Edite sua sessão" aparece primeiro e depois os Filmes ("Organize um sessão") por último.

**Comment by aluappinheiro** [comment]
Diego, me parece bem legal esta alteração em termos de rapidez de solução do problema, quanto uma melhoria na usabilidade. Vou fazer esta alteração para que deem uma olhada, se aprovam.

**Comment by diegothimm** [comment]
Issue OK
