### ISSUE TITLE
Agendamento de Sessão - seleção de data

### ISSUE THREAD

**Issue by symnat** [nucleo-digital/plataforma-taturana#155]
No agendamento de sessão, no campo “Data de Exibição”, apesar de ter a caixa do calendário para a seleção da data, se o usuário não fizer a seleção e digitar qualquer entrada no campo o sistema libera o agendamento. (Guarda a data de 31/12/1969).

**Comment by diegothimm** [comment]
O campo de Data de Exibição (Dia) ainda não está com preenchimento obrigatório.
