### ISSUE TITLE
Página de Filmes - Classificação indicativa não aparece

### ISSUE THREAD

**Issue by symnat** [nucleo-digital/plataforma-taturana#158]
A classificação indicativa não está aparecendo na página dos filmes.

**Comment by symnat** [comment]
design aqui: 
<img width="498" alt="screen shot 2016-06-16 at 18 05 41" src="https://cloud.githubusercontent.com/assets/8835807/16133406/0ce74184-33ee-11e6-95dd-e0c3445cd3d6.png">

**Comment by aluappinheiro** [comment]
Para fazer a tarefa é necessário ter as imagens de cada classe indicativa em svg ou png.

**Comment by aluappinheiro** [comment]
Preciso das imagens para poder trabalhar nesta tarefa!

**Comment by diegothimm** [comment]
Paula, as imagens estão nesse link: https://www.dropbox.com/home/fotos%20e%20quotes/Taturana-conteudo-site/icons-classificacao-filmes

**Comment by aluappinheiro** [comment]
Clico neste link e diz que esta pasta não existe.

**Comment by diegothimm** [comment]
Issue OK
