### ISSUE TITLE
Números errados nas páginas dos filmes - ATUAL FEV/2017

### ISSUE THREAD

**Issue by diegothimm** [nucleo-digital/plataforma-taturana#207]
* Comer o quê? (Número de sessões acima do real - num espectadores ok)
* Livro de Cabeceira (Número de sessões acima do real)
* Iván (Número espectadores ok - números de sessões abaixo do real)
* Se Deus Vier (Num sessões ok - número de espectadores abaixo do real)
* Piadeiros (Num de sessões acima do real - num espectadores abaixo do real)
* Nação ( num de espectadores abaixo do real - num de sessões acima do real)
* Quase Samba ( num de espectadores ok - num de sessões acima do real)
* Charlote (num de espectadores ok - num de sessões abaixo do real)
* Ilegal - num de espectadores abaixo do real.
* 20 centavos - num de espectadores abaixo do real.
* Sem pena - num de espectadores abaixo do real.
* Sp em Hi-Fi - num de sessões maior que o real.
* Freenet - num de espectadores maior que o real.
* Paratodos - num de espectadores maior que o real e de sessões abaixo do real.
* Bikes - num de sessões e espectadores abaixo do real.
* India's - num de espectadores abaixo do real.
* Elena - num de sessões abaixo do real.
* Epidemia - num de sessões abaixo do real.

**Comment by Almendary** [comment]
número anteriores à plataforma atualizados em tabela no drive:
https://docs.google.com/spreadsheets/d/1zuzBbD8qvpJwwAxCFeZTClmvDLFzJpabljSmyDcHy6c/edit?usp=drive_web

**Comment by Almendary** [comment]
Para acertar as contagens, decidimos em 02/03/2017  padronizar da seguinte forma, tanto para filmes em status "difusão" como para "difusão/portfolio", desmembrando os números em 3 frases:

xxx espectadores em xx sessões com relatório de impacto
xx sessões realizadas
xx sessões programadas (confira a agenda!)

Premissas primeira linha:
- espectadores: número de espectadores pré-plataforma + número espectadores que participaram de sessões já realizadas e com relatório pela plataforma.
- sessões com relatório de impacto: número de sessões com relatório pré-plataforma + número de sessões com relatório pela plataforma.
- rascunhos não contam em nada

Premissas segunda linha:
- todas as sessões já realizadas/passadas considerada a data presente [sessões que foram programadas e aconteceram; rascunhos não contam em nada] com dados pré-plataforma.

Premissas terceira linha:
- sessões programadas: todas as sessões do filme agendadas para o futuro em relação à data presente.

ATENÇÃO: para filmes no status apenas "portfolio", devem aparecer as contagens apenas das duas primeiras linhas.

Premissas gerais para todos os filmes:

ÍCONES DA CONTAGEM para cada linha
1 - olho
2 - calendario
3 - calendario
[layout conforme print enviado ao programador, acrescentando-se a 3a linha]

GRÁFICOS
- todas as páginas de filmes em status "difusao/portfolio" devem exibir 4 gráficos: i) dados da difusão de 4 meses; ii) regiões e municípios alcançados; iii) perfil dos embaixadores; iiii) área de atuação dos embaixadores
- incorporar os números pré-plataforma nas contagens (de regiões, municipios, categorias etc.)
- mudar o título do gráfico i para: NÚMEROS DA MOBILIZAÇÃO


Planilha com todos os dados necessários pré-plataforma
https://docs.google.com/spreadsheets/d/1zuzBbD8qvpJwwAxCFeZTClmvDLFzJpabljSmyDcHy6c/edit?usp=sharing

**Comment by Almendary** [comment]
Adds dessa leva de trabalho: se possível:
- botão da agenda na página de cada filme deveria levar apenas para a agenda do filme, e não para agenda com todos os filmes.
- subir a barra trailer e redes sociais para baixo dos botões organizar sessão | agenda de exibição
- mudar o título da home de "Democratizamos o cinema brasileiro" para:

Seja cinema, distribua arte
