### ISSUE TITLE
admin - lista embaixadores

### ISSUE THREAD

**Issue by andersoncardoso** [nucleo-digital/plataforma-taturana#38]
lista de embaixadores

> Filtrar embaixadores
>  que exibiram filme X
> que nunca agendaram sessão
> por área de atuação
> por temática
> por cidade
> por estado
> quem está com relatório pendente
> por quem solicitou participação da equipe (diretor do filme, produtor, etc.)
> 
> exportar listas em csv

**Comment by andersoncardoso** [comment]
Não é possível filtrar embaixadores por cidade ou por estado dado que o user não tem essa info.

**Comment by aluappinheiro** [comment]
Podes adicionar estas itens e fazer a filtragem
