### ISSUE TITLE
Revisar dados de filmes / gráficos

### ISSUE THREAD

**Issue by symnat** [nucleo-digital/plataforma-taturana#91]
a página do filme é essa: http://beta.taturanamobi.com.br/film/cqmfkEK2Kd5SFhzda

a planilha com os dados para os gráficos está aqui: 
https://docs.google.com/spreadsheets/d/1zuzBbD8qvpJwwAxCFeZTClmvDLFzJpabljSmyDcHy6c/edit#gid=2057388134

um exemplo de página de filme com os gráficos corretos é essa: http://beta.taturanamobi.com.br/film/MgJHFADWeWEQS4RoN

**Comment by guilhermecomum** [comment]
http://beta.taturanamobi.com.br/film/tarja-branca deve ficar assim?

**Comment by symnat** [comment]
Sim

**Comment by symnat** [comment]
Conversa do dia 21/05 - revisar modo como os dados / gráficos estão sendo alimentados pelos agendamentos.

**Comment by symnat** [comment]
Revisar para garantir que os dados dos filmes (tanto em difusão quanto portfólio) estejam de alimentando corretamente das sessões e dos relatórios.
