### ISSUE TITLE
Agendamento de filme

### ISSUE THREAD

**Issue by symnat** [nucleo-digital/plataforma-taturana#93]
No “Agendar filme” o sistema permite o envio do agendamento sem selecionar os Termos de compromisso.  

No agendamento de filmes as informações de endereço não estão como preenchimento obrigatório - Os campos como "Rua", "Número", "UF" e "País", além do "Dia" e "Horários" etc já aparacem como obrigatórios (*) mas na prática permitem o agendamento da sessão com estes campos vazios.

**Comment by symnat** [comment]
legal! não está permitindo o agendamento! só as mensagens de erro estão em inglês, rola traduzir fácil?

**Comment by guilhermecomum** [comment]
O idioma das mensagens depende da configuração de idioma do navegador. Dessa forma se o seu navegador está em inglês ele irá mostrar as mensagens em inglês!

**Comment by symnat** [comment]
excellent!
