### ISSUE TITLE
Admin logado / Visualizar sessão

### ISSUE THREAD

**Issue by symnat** [nucleo-digital/plataforma-taturana#95]
Em Gerenciar Sessões: erro ao clicar em Visualizar: 

Oops, looks like there's no route on the client or the server for url: "http://beta.taturanamobi.com.br/adm/session/."

> abrir dados da sessão em uma janela pop-up

**Comment by guilhermecomum** [comment]
Arrumei mas enviando para um nova página como havia sido programado antes
