### ISSUE TITLE
Embaixador Logado / Minhas informações

### ISSUE THREAD

**Issue by symnat** [nucleo-digital/plataforma-taturana#97]
http://testes.taturanamobi.com.br/ambassador-edit

No cabeçalho "undefinedundefinedundefinedundefinedundefinedundefinedundefined200 pessoas impactadas pela difusão de filmes"

onde deveria aparecer o número de pessoas impactadas pelas sessões organizadas pelo embaixador (soma do total de pessoas das sessões organizadas pelo embaixador a partir dos relatórios enviados por ele)

**Comment by guilhermecomum** [comment]
Não consigo reproduzir! Isso continua acontecendo?
Pode me mandar um screenshot?
