### ISSUE TITLE
Admin Sessões - diferenciar sessões passadas de sessões agendadas

### ISSUE THREAD

**Issue by symnat** [nucleo-digital/plataforma-taturana#98]
Não há design ainda, vou produzir um esquema de como deve ficar

**Comment by symnat** [comment]
feito, passei link

**Comment by guilhermecomum** [comment]
A plataforma só mostra sessões futuras

**Comment by symnat** [comment]
Sessões agendadas com ícone de sessão agendada.
Só aparece o ícone de relatório depois que a data da sessão passar.
