### ISSUE TITLE
Admin Sessões - Relatórios pendentes

### ISSUE THREAD

**Issue by symnat** [nucleo-digital/plataforma-taturana#99]
Admin precisa identificar qual é o relatório pendente de cada embaixador.

Hoje tem o filtro "Tem relatório pendente" em Gerencie Embaixadores, porém isso não permite que as clientes vejam a qual sessão se refere.

**Comment by guilhermecomum** [comment]
O admin pode pegar essa informação em "Gerenciar Sessões" com o novo filtro implementando no ticket #94

**Comment by symnat** [comment]
Bacana, só uma questão: quando clica em "Tem relatórios pendentes?", está mostrando as sessões cujo relatório já foi enviado, enquanto que precisaria mostrar as sessões que tem o relatório pendente (!).
